name: anc_acyl
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - python
  - openbabel
  - biotite
  - seaborn
  - matplotlib
  - mdanalysis
  - scikit-learn
  - pymol-open-source
